kind: pipeline
name: default

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn clean package
    volumes:
      - name: m2
        path: /root/.m2
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    volumes:
        - name: sonar
          path: /root/.sonar
    settings:
      sonar_host:
        from_secret: sonar-host
      sonar_token:
        from_secret: sonar-secret

volumes:
  - name: m2
    host:
      path: /data/drone/.m2
  - name: sonar
    host:
      path: /data/drone/.sonar
