version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --init-file /data/sql/user.sql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/data/sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: test
    ports:
      - 13306:3306
  backend:
    build: ./
    image: spring-boot-exercise:build
  nginx:
    build: ./web
    image: spring-boot-exercise-web:build
    ports:
      - 8888:8888
